name: CI Pipeline

on:
  push:
    branches: [ "staging", "master" ]
  pull_request:
    branches: [ "staging", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: vacancestranquillesdb
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd="pg_isready -U admin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/vacancestranquillesdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Run frontend tests
        working-directory: frontend
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build frontend
        working-directory: frontend
        run: npm run build -- --configuration=production

      - name: Build backend
        working-directory: backend
        run: mvn clean install

      - name: Run backend tests
        working-directory: backend
        run: mvn test